// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElIconBack: typeof import('@element-plus/icons-vue')['Back']
    ElIconCircleClose: typeof import('@element-plus/icons-vue')['CircleClose']
    ElIconClose: typeof import('@element-plus/icons-vue')['Close']
    ElIconDArrowLeft: typeof import('@element-plus/icons-vue')['DArrowLeft']
    ElIconDArrowRight: typeof import('@element-plus/icons-vue')['DArrowRight']
    ElIconEdit: typeof import('@element-plus/icons-vue')['Edit']
    ElIconMenu: typeof import('@element-plus/icons-vue')['Menu']
    ElIconRefresh: typeof import('@element-plus/icons-vue')['Refresh']
    ElIconRefreshRight: typeof import('@element-plus/icons-vue')['RefreshRight']
    ElIconRight: typeof import('@element-plus/icons-vue')['Right']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../src/components/SvgIcon/index.vue')['default']
  }
}
